In [5]:
#1. What is a Python library? Why do we use Python libraries?

#Solution:
#Python libraries are collections of reusable code modules that you can integrate into your projects to save time and effort. 
#They are like a toolbox, each providing different tools that can be used to perform various tasks efficiently.
#Making use of Python libraries makes it convenient for the programmer as they wouldn't have to write the same code multiple times
#for different programs.

In [7]:
#2.What is the difference between Numpy array and List?
#Soltion: List:

#A list is a built-in, linear data structure of Python. It is used to store the data in a sequence manner.
#We can perform several operations to list, such as indexing, iterating, and slicing. The list comes with the following features.

#>The list elements are enclosed with a square bracket, and each element is separated by a comma (,).
#>It is a mutable type which means we can modify the list items after their creation.
#>The lists are ordered, which means items are stored in a specific order. We can use indexing to access the list element.
#>We can store the items of different data types. We can combine strings, integers, and objects in the same list.

#Array

#An array is also a linear data structure that stores the data. It is also ordered, mutable, and enclosed in square brackets. 
#It can store the non-unique items. But there are restrictions to store the different data type values.
#To work with the Array in Python, we need to import either an array module or a Numpy.

In [12]:
#3. Find the shape, size and dimension of the following array?
arr1=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [14]:
import numpy as np
arr1=np.array(arr1)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
#shape
arr1.shape

(3, 4)

In [16]:
#size
arr1.size

12

In [17]:
#dimension
arr1.ndim

2

In [18]:
#4. Write python code to access the first row of the following array?
arr=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [19]:
arr=np.array(arr)

In [20]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr[0]

array([1, 2, 3, 4])

In [22]:
#5. How do you access the element at the third row and fourth column from the given numpy array?
arr=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [26]:
arr=np.array(arr)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr[2,3]

12

In [29]:
#6. Write code to extract all odd-indexed elements from the given numpy array?
arr3=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [30]:
arr3=np.array(arr3)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
arr3[np.sum(np.indices(arr.shape), axis=0) % 2 != 0]

array([ 2,  4,  5,  7, 10, 12])

In [ ]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [43]:
arr1 = np.random.randint(0, 1, (3,3))
arr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [44]:
#8. Describe the difference between np.random.rand and np.random.randn?

#The numpy.random.rand() function creates an array of specified shapes fills it with random values and generates random numbers with Numpy.
#ex:
import random
np.random.rand(2, 3)

array([[0.62607115, 0.14848446, 0.44894462],
       [0.12793854, 0.48176384, 0.95116382]])

In [45]:
#The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution
np.random.randn(2, 3)

array([[-0.71433404,  1.48917227, -0.77523029],
       [ 0.23865933, -0.93174241,  1.34494624]])

In [46]:
#9. Write code to increase the dimension of the following array?
arr=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [90]:
arr=np.array(arr)
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
#expand_dims >>expand the dimension of array
arr1= np.expand_dims(arr, axis = 0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [47]:
#10. How to transpose the following array in NumPy?
arr1=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [50]:
arr1=np.array(arr1)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
arr1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [52]:
#11. Consi^er the following matrix:
#Matrix A :[[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
#Matrix B: [[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]]

#Perform the following operation using Python1
#1.Index wiLe multiplication
#2.Matix multiplication
#3.Add both the matix
#4.Subtact matix B from A 
#5.Divide Matix B by A

In [71]:
arrA=[[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
arrB=[[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]]
arrA=np.array(arrA)
arrB=np.array(arrB)

In [72]:
arrA

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
arrB

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
#Index wiLe multiplication
index=arrA*arrB
index

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [75]:
# Multiplication matrix not possible because in m*n and p*q, n and q is not equal
multiplication=arrA @ arrB
multiplication

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [93]:
#Add both the matics
Add=arrA+arrB
Add

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [94]:
#Subtact matix B from A
Sub=arrA-arrB
Sub

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [95]:
#Diide Matix B by A
Div=arrA/arrB
Div

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [82]:
#12. Which function in Numpy can be used to swap the byte order of an array?
#Sol:
# byteswap() method swaps the bytes of the array elements. 
# It toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place.

In [83]:
#13.What is the significance of the np.linalg.inv function?
#Sol:
# NumPy linalg. inv() function in Python is used to compute the (multiplicative) inverse of a matrix.

In [84]:
#14.What does the np.reshape function do, and how is it used?
#SOl:
#The numpy. reshape() function allows us to reshape an array in Python. Reshaping basically means, changing the shape of an array.

#example:
arr = np.random.randint(1, 5, size = (3, 4))
arr

array([[3, 4, 2, 2],
       [1, 2, 4, 3],
       [1, 1, 2, 1]])

In [85]:
arr.size

12

In [86]:
arr.shape

(3, 4)

In [87]:
arr.reshape(2, 6)#array size can not change, multiples of array size

array([[3, 4, 2, 2, 1, 2],
       [4, 3, 1, 1, 2, 1]])

In [88]:
#15. What is broadcasting in Numpy?
#Sol:
# the ability of NumPy to treat arrays of different shapes during arithmetic operations.

arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])